Fix ant speed and 0th challenge completions in c13
Pseudo-Corp/SynergismOfficial pull request #120
Opened 2021-07-27 17:57 UTC by luciscout

2021-07-27 18:06 UTC, AreYouKittenMe commented
Please check this before my #119, it includes my quickfix, making mine unnecessary if approved.

2021-07-27 18:07 UTC, KhafraDev requested changes

2021-07-27 18:07 UTC, KhafraDev commented on dist/out.js
> +(()=>{var xa=Object.create;var cn=Object.defineProperty;var Ma=Object.getOwnPropertyDescriptor;var Ea=Object.getOwnPropertyNames,ds=Object.getOwnPropertySymbols,Ba=Object.getPrototypeOf,ms=Object.pro
this file needs to be removed

2021-07-27 18:40 UTC, luciscout commented on dist/out.js
> +(()=>{var xa=Object.create;var cn=Object.defineProperty;var Ma=Object.getOwnPropertyDescriptor;var Ea=Object.getOwnPropertyNames,ds=Object.getOwnPropertySymbols,Ba=Object.getPrototypeOf,ms=Object.pro
File has been removed

2021-08-24 07:22 UTC, memcculloch approved these changes
Changing index has no effect?

2021-08-24 07:22 UTC, memcculloch commented on src/Tax.ts
> +        exp *= Math.pow(1.05, Math.max(0, sumContents(player.challengecompletions) - player.challengecompletions[0] - player.challengecompletions[11] - player.challengecompletions[12] - player.challe
Stick the calculations on seperate lines so it's easier to review. Confirm that the change is subtracting player.challengecompletions[0] from the exp.

2021-08-24 07:22 UTC, memcculloch commented on src/Tax.ts
> +        exp *= Math.pow(1.05, Math.max(0, sumContents(player.challengecompletions) - player.challengecompletions[0] - player.challengecompletions[11] - player.challengecompletions[12] - player.challe
Didn't see the above comment, add comments for changes like that to the PR instead of in code please

2021-08-24 07:22 UTC, memcculloch commented on src/Synergism.ts
> +    G['globalAntMult'] = G['globalAntMult'].times(Decimal.pow(1.12 + player.researches[101] / 1000 + player.researches[162] / 10000, player.antUpgrades[1-1] + G['bonusant1']));
Change in base power could have results on the game, preferably this would be in a constant so changes could be discussed there on overall effect.

2021-08-24 07:22 UTC, memcculloch commented on src/Tax.ts
> +    G['taxdivisor'] = Decimal.pow(1.01, (c) * (exponent));
Switching from variable compareB to c, could use a comment on the effects

2021-08-24 07:24 UTC, memcculloch approved these changes
Worry is on the reset changes to initial index might have side effects, otherwise see suggestions

2023-02-19 20:36 UTC, closed without merging