Improve Singularity Tab UI
Pseudo-Corp/SynergismOfficial pull request #175
Opened 2022-05-20 01:22 UTC by FlamemasterNXF

2022-05-20 01:33 UTC, KhafraDev requested changes
1. `.idea` folder needs to be removed
2. `index.html` changes should be reverted
3. `.innerHTML` needs to go, manually create the elements and use `appendChild` (etc.) instead.

2022-05-20 01:36 UTC, FlamemasterNXF commented
> 2. `index.html` changes should be reverted

The only changes I made there were to give the sing upgrades a class that gave them margins and to slightly reorganizes the sing upgrades. Where is the issue with those changes?

2022-05-20 01:37 UTC, KhafraDev commented
> Where is the issue with those changes?

There's about 8.6 thousand changes due to an indentation change afaict

2022-05-20 01:38 UTC, FlamemasterNXF commented
> > Where is the issue with those changes?
> 
> There's about 8.6 thousand changes due to an indentation change afaict

Oh geez, WebStorm must've reformatted it. I will fix that immediately.

2022-05-20 01:46 UTC, FlamemasterNXF commented
@KhafraDev have the 8.6k changes gone away?

2022-05-20 02:08 UTC, KhafraDev requested changes
also needs a rebase (innerhtml changes are fine for now)

2022-05-20 02:08 UTC, KhafraDev commented on src/singularity.ts
> +    const color = player.runelevels[6]>0?'green':'red'
```suggestion
    const color = player.runelevels[6] > 0 ? 'green' : 'red';
```

2022-05-20 02:08 UTC, KhafraDev commented on src/singularity.ts
> +        const color = this.maxLevel === this.level?'plum':'white'
```suggestion
        const color = this.maxLevel === this.level ? 'plum' : 'white';
```

2022-05-20 02:15 UTC, FlamemasterNXF commented
What commit am I rebasing to? (sorry if this is obvious, I don't use rebase often)

2022-05-20 02:34 UTC, KhafraDev commented
15ac1cc98794069ebc1433151326a87ee738759f

2022-05-20 02:38 UTC, KhafraDev approved these changes

2022-05-23 23:07 UTC, Pseudonian commented
LGTM

2022-05-23 23:07 UTC, merged