Colors for if you meet minimum singularity for singularity upgrades
Pseudo-Corp/SynergismOfficial pull request #214
Opened 2022-06-20 13:11 UTC by ArvingoMaster

2022-06-20 14:13 UTC, KhafraDev approved these changes

2022-06-21 04:14 UTC, KhafraDev requested changes
lint

2022-06-21 07:16 UTC, ArvingoMaster commented
I reverted that change, was meant for a different pr, lint should work now

2022-06-21 14:43 UTC, KhafraDev approved these changes

2022-06-21 19:15 UTC, merged