introduce notations
Pseudo-Corp/SynergismOfficial pull request #388
Opened 2022-10-28 17:28 UTC by Vonuras

* Pure Scientific -> if the exponent is bigger than 1e6 it will be displayed as "E1.111e8"
* Pure Engineering -> same as Scientific but only shows multiples of 3 as exponent
* Toggle like the Themes within settings
* refactored some other functions within format

2022-10-28 17:34 UTC, Vonuras commented
I will actually revise this, once some of the other Pull Request are merged, as there are a lot of approved PRs, that are not merged yet, and some of them are interconnected to these changes

2022-11-07 21:02 UTC, KhafraDev requested changes
Looks good so far, just a few style things need to be addressed

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +function letter(power: number,str: string[]) {
```suggestion
function letter(power: number, str: string[]) {
```

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +            result = len*result+1;
```suggestion
            result = len * result + 1;
```

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +    while (power >= lN(++i)){}
```suggestion
    while (power >= lN(++i));
```

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +    let i=0;
```suggestion
    let i = 0;
```

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +        ret += str[Math.floor(power/Math.pow(len,--i))%len];
```suggestion
    while (i > 0) {
        ret += str[Math.floor(power/Math.pow(len,--i)) % len];
```

2022-11-07 21:02 UTC, KhafraDev commented on src/Synergism.ts
> +    if (power < 1e6) {
```suggestion
    } else if (power < 1e6) {
```

2022-11-08 11:44 UTC, Vonuras commented on src/Synergism.ts
> +    if (player.notation == 'Pure Scientific' || player.notation == 'Pure Engineering') {
This actually needs to be just an if, as there is a case, where you want the first if and this one to trigger

2022-11-08 15:17 UTC, Vonuras commented on src/Synergism.ts
> +    if (player.notation == 'Pure Scientific' || player.notation == 'Pure Engineering') {
No I know
There is an if at line 1967 (first if), and if you change the if at 1971/1972 (second if) to be an else if, you would not run the code which is inside both ifs, while having notation be 'Pure Scientific'

2022-11-08 15:24 UTC, KhafraDev commented on src/Synergism.ts
> +    if (i == 1) {
```suggestion
    if (i === 1) {
```

2022-11-08 15:25 UTC, KhafraDev commented on src/Synergism.ts
> +    if (power >= 1e6) {
this doesn't seem to be resolved

2022-11-08 15:29 UTC, Vonuras commented on src/Synergism.ts
> +    if (i == 1) {
done

2022-11-08 15:32 UTC, KhafraDev approved these changes

2022-11-08 15:35 UTC, KhafraDev commented
CI is failing because of one of my suggestions, sorry about that

2022-11-08 15:38 UTC, KhafraDev commented on src/Synergism.ts
> +const supportsFormatToParts = typeof (Intl.NumberFormat.prototype ).formatToParts === 'function';
this needs to be reverted

2022-11-08 15:43 UTC, merged