Exalt UI Overhaul
Pseudo-Corp/SynergismOfficial pull request #594
Opened 2024-05-09 01:42 UTC by Mixelz

Oh boy another Mixelz UI Overhaul on a Singularity mechanic! **What are the odds!!!**
Changes were implemented to be as unobtrusive as possible, only 2 additional variables for EXALT challenges are required for this.
Ideally we'd also showcase current completion # under the icons like normal challenges & current effect % as well but I am not a good enough programming wizard to implement this. If anyone else wants to take a shot please do so.

## Primary Changes
- EXALT is now a Subtab of Challenges, subtabs are hidden until Exalts are unlocked normally (Sing 25).
  - Above change includes removing EXALT subtab from Singularity Tab and shifting everything required over by one (I hopefully learned my lesson from the Perk/Penalties merge).
- EXALT Rewards are now visually split between **Scaling Rewards** and **Unique Rewards**.
  - Above change includes having an bulletpoint list for all rewards in an exalt (Much easier to read than one run on sentence).
- EXALT Icons now react to the cursor (Cursor Change + Icon Highlight. WOW!!!!1!)
- EXALT Info reorganized for easier reading.

![image](https://github.com/Pseudo-Corp/SynergismOfficial/assets/32188067/a66e3f2e-f0df-4aea-b57f-d7bb372173e9)

2024-05-09 02:05 UTC, KhafraDev requested changes

2024-05-09 02:05 UTC, KhafraDev commented on src/SingularityChallenges.ts
> +  ScaleString (): string {
```suggestion
  scaleString (): string {
```

2024-05-09 02:05 UTC, KhafraDev commented on src/SingularityChallenges.ts
> +  UniqueString (): string {
```suggestion
  uniqueString (): string {
```

2024-05-09 02:09 UTC, Mixelz commented on src/SingularityChallenges.ts
> +  UniqueString (): string {
Implmented in follow up commit

2024-05-09 02:09 UTC, Mixelz commented on src/SingularityChallenges.ts
> +  ScaleString (): string {
Implmented in follow up commit

2024-05-23 04:21 UTC, KhafraDev requested changes

2024-05-23 04:21 UTC, KhafraDev commented on src/SingularityChallenges.ts
> +     if (i > this.scalingrewardcount) {}
this does nothing

2024-05-23 04:21 UTC, KhafraDev commented on src/SingularityChallenges.ts
> +     if (i > this.scalingrewardcount) {}
same here

2024-05-23 05:20 UTC, Mixelz commented on src/SingularityChallenges.ts
> +     if (i > this.scalingrewardcount) {}
Resolved with commit

2024-05-23 05:22 UTC, Mixelz commented on src/SingularityChallenges.ts
> +     if (i > this.scalingrewardcount) {}
Resolved with commit

2024-05-29 03:58 UTC, merged