Change background color of platonic upgrades if they are partially or fully upgraded.
Pseudo-Corp/SynergismOfficial pull request #79
Opened 2021-07-05 21:00 UTC by eyebrowsoffire

2021-07-05 21:08 UTC, KhafraDev requested changes

2021-07-05 21:08 UTC, KhafraDev commented on src/Synergism.ts
> +        for (let j = 1; j <= 20; j++) {
```suggestion
        const platUpg = document.querySelectorAll('img[id^="platUpg"]');
        for (let j = 1; j <= platUpg.length; j++) {
```

that way other elements can be added in the future without having to change the hardcoded number of elements

2021-07-05 21:08 UTC, KhafraDev commented on src/Platonic.ts
> +    if (player.platonicUpgrades[i] > 0 && player.platonicUpgrades[i] < maxLevel) {
```suggestion
    else if (player.platonicUpgrades[i] > 0 && player.platonicUpgrades[i] < maxLevel) {
```

2021-07-05 21:08 UTC, KhafraDev commented on src/Platonic.ts
> +    if (player.platonicUpgrades[i] === maxLevel) {
```suggestion
    else if (player.platonicUpgrades[i] === maxLevel) {
```

2021-07-05 21:08 UTC, KhafraDev commented on src/Platonic.ts
> +    const a = document.getElementById("platUpg" + i)
```suggestion
    const a = document.getElementById(`platUpg${i}`)
```

2021-07-05 21:46 UTC, eyebrowsoffire commented
Applied your suggestions and restested the changes.

2021-07-05 21:48 UTC, KhafraDev approved these changes

2021-07-10 16:55 UTC, Pseudonian commented
Looks solid. Great work :)

2021-07-10 16:55 UTC, merged